dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer require typo3/cms="$TYPO3_VERSION"

script:
  - composer test

jobs:
  fast_finish: true
  include:
    - php: 5.6
      env: TYPO3_VERSION=^7.6
      before_install:
        # Not compatible to PHP 5.6
        - composer remove --no-update --dev slevomat/coding-standard
      script:
        - composer lint:php
        - composer test
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^8.7

    - &lint
      php: 7.0
      env: PHP lint
      install:
        - composer install
      script:
        - composer lint:php
    - <<: *lint
      env: XML lint
      script:
        - composer lint:xml
    - <<: *lint
      env: Codestyle
      script:
        - composer lint:style

    - stage: deploy
      if: tag IS present
      php: 7.1
      before_install: skip
      install: skip
      before_script: skip
      script: |
        echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"
        EXTENSION_KEY="$(composer config extra.typo3/cms.extension-key)"

        export PATH=$PATH:$(composer global config bin-dir --absolute 2>/dev/null)
        git reset --hard
        git clean -xfd

        echo "Creating phar files for vendors"

        composer global require clue/phar-composer

        mkdir -p /tmp/vendors
        pushd /tmp/vendors
        composer require symfony/workflow:^3.3 mpdf/mpdf:^6.1
        rm -rf vendor/mpdf/mpdf/ttfonts
        phar-composer build .
        popd
        cp /tmp/vendors/vendors.phar .
        echo "require 'phar://' . \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('${EXTENSION_KEY}') . '/vendors.phar/vendor/autoload.php';" >> ext_localconf.php

        composer global require helhum/ter-client dev-master

        echo "Uploading release ${TRAVIS_TAG} to TER"
        ter-client upload "$EXTENSION_KEY" . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"

notifications:
  slack:
    secure: TPgLYBAyIa6V6RT3YqndCnpkiifnY01ehmPrhVHU3G3yC4e4PtnqftgCrg8D4IBbmlVTxncNbsDqNbFfBEaJ1dMv6tv0yMpYlllfN5Syl3nBcjh43rHN4DWEffgJ59dAhJJtWjHvPfYR1/80EdKzsmepQl1i1+CXH1ryxtS6jEU=
