dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - bin/parallel-lint --exclude bin --exclude vendor --exclude web .
  - bin/phpunit

jobs:
  include:
    - php: 7.0
    - php: 5.6
      before_install:
        # Not compatible to PHP 5.6
        - composer remove --dev slevomat/coding-standard
    - php: 7.1
      env: Other lints
      script:
        - bin/xmllint --pattern "*.xlf*,svg" Resources
    - php: 7.1
      env: Codestyle
      script:
        - bin/phpcs

    - stage: deploy
      if: tag IS present
      php: 7.1
      before_install: skip
      install: skip
      before_script: skip
      script: |
        echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"

        git reset --hard
        git clean -xfd

        echo "Creating phar files for vendors"

        composer global require clue/phar-composer

        mkdir -p /tmp/vendors
        pushd /tmp/vendors
        composer require symfony/workflow:^3.3 mpdf/mpdf:^6.1
        rm -rf vendor/mpdf/mpdf/ttfonts
        phar-composer build .
        popd
        cp /tmp/vendors/vendors.phar .

        export PATH=$PATH:$(composer global config bin-dir --absolute 2>/dev/null)
        composer global require helhum/ter-client dev-master

        echo "Uploading release ${TRAVIS_TAG} to TER"
        ter-client upload $(composer config extra.typo3/cms.extension-key) . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"

notifications:
  slack:
    secure: TPgLYBAyIa6V6RT3YqndCnpkiifnY01ehmPrhVHU3G3yC4e4PtnqftgCrg8D4IBbmlVTxncNbsDqNbFfBEaJ1dMv6tv0yMpYlllfN5Syl3nBcjh43rHN4DWEffgJ59dAhJJtWjHvPfYR1/80EdKzsmepQl1i1+CXH1ryxtS6jEU=
