dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

jobs:
  fast_finish: true
  include:
    - &test
      php: 7.0
      env: TYPO3_VERSION=^8.7
      install:
        - composer require typo3/cms="$TYPO3_VERSION"
      script:
        - composer lint:php
        - composer test
        
    - <<: *test
      env: TYPO3_VERSION=^7.6
      
    - <<: *test
      php: 5.6
      env: TYPO3_VERSION=^7.6
      before_install:
        # Not compatible to PHP 5.6
        - composer remove --no-update --dev slevomat/coding-standard

    - php: 7.0
      env: XML lint
      script:
        - composer lint:xml
    - php: 7.0
      env: Codestyle
      script:
        - composer lint:style

    - stage: deploy
      if: tag IS present
      php: 5.6
      before_install: skip
      install: skip
      before_script: skip
      script: |
        echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"
        EXTENSION_KEY="$(composer config extra.typo3/cms.extension-key)"

        export PATH=$PATH:$(composer global config bin-dir --absolute 2>/dev/null)
        git reset --hard
        git clean -xfd

        echo "Creating phar files for vendors"

        composer global require clue/phar-composer

        mkdir -p /tmp/vendors
        pushd /tmp/vendors
        composer require symfony/workflow:^3.3 mpdf/mpdf:^6.1
        rm -rf vendor/mpdf/mpdf/ttfonts
        phar-composer build .
        popd
        cp /tmp/vendors/vendors.phar .
        echo "require 'phar://' . \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('${EXTENSION_KEY}') . 'vendors.phar/vendor/autoload.php';" >> ext_localconf.php

        composer global require helhum/ter-client

        echo "Uploading release ${TRAVIS_TAG} to TER"
        ter-client upload "$EXTENSION_KEY" . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"

notifications:
  slack:
    secure: etwZGCoF90eFoIEyJ73UDeHq37NpUxwolIjzy+ymCPpUyymy4nuWsJzf26gbUEAwDVlc0ysfLvrg1ppBkTimZeuwsktV5OWLOyz6mnthPmPMeyzG+rS4yiQV1pGTfyz4pEixJTQnNI51Ep6NbqBhvHOkM2+PyFoRiuy6qeW4nLTztWO4WPJFP9B2Oo9O8otabw3Gjmdft8RujYPciRgX7PpSR5AY5hGz1DN/VOYsPb8bRpiigYPsicYeus0lTuKFchHZqk9XWQ2x6k9Sh/ScVmqdGaEl6d0lMMDoWZ/wxFKiLLLqdQiP5db4HJ+W2OPABRQ1zbovJaE3xac9GICS/yRfJv+KIuVHnB3zvuwMcC20c4NUI5hL+QzUm63aZ+1eJs019DZPS+Dj3y8E8OTkNyyorenBea4J0+dXgwFRwC8y8C13Jt/ASPCFghQE9A8Z2dMi4v0rMrEwSDX/xuBezhCKNLy+pSt0YmDWeh5YbwikJHrdjQbqat+vehFORaS7c4yJlssiokIjXDWilbWaDcgCTLQfmBzK4UCu48j0g+3n81Zjw6VIHrsTiBx1jt3QYCY3ospI+r1pUC1iLOUNyNBfHo4GsznJn5ge1HDnYPpY8aWUaBmiD8+0h6oapChDN8PLzQdDlaFq02Z8Iw3VYUz8HbmakB2n+GsNCjQ9X2E=
